# Generated by Django 4.1 on 2022-08-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0003_auto_20220806_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
